title: blog2epub
logo: /assets/blog2epub.svg
description: Convert blog to epub using command line or GUI

author:
  name: Bohdan Bobrowski
  email: "bohdanbobrowski@gmail.com"

email: "bohdanbobrowski@gmail.com"
twitter_username: BohdanBobrowski
github_username: bohdanbobrowski
repository_name: blog2epub

url: https://bohdanbobrowski.github.io
baseurl: /blog2epub

permalink: pretty
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "assets/"

exclude:
  - vendor/
  - Gemfile
  - LICENSE
  - Makefile
  - README.md
  - blog2epub
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true

skin: solarized-dark
header_pages:
  - changelog.md
  - covers.md
  - screenshots.md
  - todo.md

minima:
  social_links:
    - { platform: flickr,         user_url: "https://flickr.com/photos/bodzio" }
    - { platform: github,         user_url: "https://github.com/bohdanbobrowski" }
    - { platform: instagram,      user_url: "https://instagram.com/bohdan.bobrowski/" }
    - { platform: linkedin,       user_url: "https://linkedin.com/in/bohdanbobrowski/" }
    - { platform: twitter,        user_url: "https://twitter.com/BohdanBobrowski" }
    - { platform: youtube,        user_url: "https://youtube.com/channel/UCjCqjVqCoTIpzaa9fn2bpXQ" }
