title: blog2epub
logo: /assets/blog2epub_256px.png
description: Convert blog to epub using command line or GUI.
show_downloads: true
google_analytics:
theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false