text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
title : blog2epub
description: > # this means to ignore newlines until "Language & timezone"
  Convert blog to epub using command line or GUI

lang: en
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

author:
  type: person
  name: Bohdan Bobrowski
  url:
  avatar:
  bio: Python developer.
  email: bohdanbobrowski@gmail.com
  twitter: BohdanBobrowski
  linkedin: bohdanbobrowski
  github: bohdanbobrowski

repository: bohdanbobrowski/blog2epub
repository_tree: master

paths:
  root: # title link url, "/" (default)
  home: # home layout url, "/" (default)
  archive:  # "/archive.html" (default)
  rss: # "/feed.xml" (default)

excerpt_separator: <!--more-->

license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

toc:
  selectors: # "h1,h2,h3" (default)

mathjax: # false (default), true
mathjax_autoNumber: # false (default), true
mermaid: # false (default), true
chart: # false (default), true
paginate: 8
paginate_path: /page:num # don't change this unless for special need
sources: # bootcdn (default), unpkg

sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

pageview:
  provider: false # false (default), "leancloud", "custom"
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class

search:
  provider: default # "default" (default), false, "google", "custom"
  google:
    custom_search_engine_id: # Google Custom Search Engine ID

analytics:
  provider: false # false (default), "google", "custom"
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics

markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - /assets
  - /blog2epub
  - /packages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji