title: blog2epub
logo: /assets/blog2epub_256px.png
description: Convert blog to epub using command line or GUI.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
gems:
  - jekyll-readme-index
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false