[tool.ruff.lint.extend-per-file-ignores]
"blog2epub_kivy.py" = ["E402"]
[tool.poetry]
name = "blog2epub"
version = "1.3.0"
description = "Convert blog (blogspot.com, wordpress.com or another based on Wordpress) to epub using command line or GUI."
authors = ["Bohdan Bobrowski <bohdanbobrowski@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kivymd = "^1.2.0"
pydantic = "^2.8.2"
beautifulsoup4 = "^4.12.3"
ebooklib = "^0.18"
python-dateutil = "^2.9.0.post0"
atoma = "^0.0.17"
fake-useragent = "^1.5.1"
pyyaml = "^6.0.1"
pycairo = "^1.26.1"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
